name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZIP custom_component
        run: |
          zip -r absolute_humidity.zip custom_components/Absolute-Humidity-Helper
          cd ..
      - name: ZIP custom_component
        run: |
            cd custom_components
            if [ -d "absolute_humidity" ]; then
                zip -r ../absolute_humidity.zip absolute_humidity
            else
                echo "Error: absolute_humidity directory not found in custom_components"
                ls -la
                exit 1
           fi
            cd ..
   
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: absolute_humidity.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
